### ISSUE TITLE
rename @Load -> @inject

### ISSUE THREAD

**Issue by ethernian** [dapplets/dapplet-modules#5]
The name `@inject` may be more suitable as the current `@Load`, because it is a dependency injection (DI) actually. 
Later we may switch to [inversify](https://inversify.io). It makes sense to use the same naming scheme for DI already now. 
 
https://github.com/dapplets/typescript-examples/blob/40d0fa8cf4d2aaaf16d4f7fad46a357fd61c8f56/src/TwitterFeature2/index.ts#L88-L89

**Comment by alsakhaev** [comment]
renamed
